---
- name: Upload RPMs to repo Branched
  hosts: all
  become: true

  tasks:
    - name: satellite integrate
      redhat.satellite.content_upload:
        username: "admin"
        password: "redhat"
        server_url: "https://sat614.example.com"
        organization: "Red Hat"
        product: "myproduct"
        repository: "myrepo"
        src: "{{ item }}"
      loop: "{{ myrepo.rpm_names }}"
