---
- name: Upload RPMs to repo Branched
  hosts: all
  - tasks: satellite integrate
    redhat.satellite.content_upload:
       username: "admin"
       password: "redhat"
       server_url: "https://sat614.example.com"
       organization: "Red Hat"
       product: "myproduct"
       repository: "myrepo"
       src: "https://github.com/Afridv02/satellite/blob/main/24.2.20-2091_illumio-ven-24.2.20-2091.c8.x86_64.rpm"
       loop: "{{ myrepo.rpm_names }}"
       become: true
