---
- name: Upload rpms to repo Branched
  hosts: all
  collections:
    - redhat.satellite
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Upload RPM to Satellite
      redhat.satellite.content_upload:
        username: "{{ sat_admin_user }}"
        password: "{{ satgitops_admin_password }}"
        server_url: "{{ sat_url }}"
        organization: "{{ sat_organization }}"
        validate_certs: false
        product: "{{ to_sat_product }}"
        repository: "{{ to_sat_repo }}"
        src: "/tmp/{{ item }}"
       
